apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/srgrdn/incident-monitor/api
    newTag: 0.1.0
  - name: ghcr.io/srgrdn/incident-monitor/worker
    newTag: 0.1.0
