apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/srgrdn/incident-monitor/api
    newTag: 589f60f7432e6de8aa96a48773d11b5f9fb0871d
  - name: ghcr.io/srgrdn/incident-monitor/worker
    newTag: 589f60f7432e6de8aa96a48773d11b5f9fb0871d
