apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/srgrdn/incident-monitor/api
    newTag: 16f6dc90de8dd022bf5c91510d2fec1947dcfe2b
  - name: ghcr.io/srgrdn/incident-monitor/worker
    newTag: 16f6dc90de8dd022bf5c91510d2fec1947dcfe2b
