apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-worker
  namespace: incident-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incident-worker
  template:
    metadata:
      labels:
        app: incident-worker
    spec:
      imagePullSecrets:
        - name: ghcr-registry
      containers:
        - name: worker
          image: ghcr.io/srgrdn/incident-monitor/worker:0.1.0
          env:
            - name: API_URL
              value: http://incident-api:8080
            - name: INTERVAL_SECONDS
              value: "30"
