apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-api
  namespace: incident-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incident-api
  template:
    metadata:
      labels:
        app: incident-api
    spec:
      containers:
        - name: api
          image: ghcr.io/srgrdn/incident-monitor/api:0.1.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
